name: Release

on:
  push:
    tags: ['**']


permissions:
  contents: write


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          tar -czf fci-breeds.tar.gz *.csv

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: fci-breeds.tar.gz
